# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder "/home/Student/sources/", "/vagrant/sources/",
	owner: "root", group: "root",
	create: true	

  config.vm.define "app" do |app|
        app.vm.box = "sbeliakou/centos-6.7-x86_64"
        app.vm.hostname = "app"
        app.vm.network "private_network", ip: "192.168.33.15"
        app.vm.provider "virtualbox" do |mashine|
                mashine.name = "app"
                mashine.memory = "1024"
                mashine.customize ["modifyvm", :id, "--cpuexecutioncap", "35"]
        end
        app.vm.provision "shell", path: "app.sh"
  end


  config.vm.define "web" do |web|
	web.vm.box = "sbeliakou/centos-6.7-x86_64"
	web.vm.hostname = "web"
	web.vm.network "private_network", ip: "192.168.33.10"
	web.vm.provider "virtualbox" do |mashine|
		mashine.name = "web"
		mashine.memory = "512"
		mashine.cpus = 1
	end
	web.vm.provision "shell", path: "web.sh"
  end

  config.vm.provision "shell", inline: <<-SHELL
	yum install -y vim
  SHELL
  
end
